### ISSUE TITLE
Not able to delete last chosenMultiple Item

### ISSUE THREAD

**Issue by PaulNokel** [janisto/yii-ycm#5]
Hi,

it does seem to be impossible to delete the last item of an input with type "chosenMultiple".
I got the following:
attributeWidgets() => array('sunday','chosenMultiple'),
beforeSave() => $this->sunday = json_encode($this->sunday);
afterFind() => $this->sunday = json_decode($this->sunday);
sundayChoices() => array("00:00" => "00:00" etc...)

What am i missing here?

**Comment by janisto** [comment]
I updated chosen to latest version. Is it now working for you?

**Comment by PaulNokel** [comment]
Thanks for the update. I investigated a bit further and found my mistake... Using $this->input in beforeSave() and expecting the $_POST value was not very clever :D

**Comment by janisto** [comment]
It happens ;)
