### ISSUE TITLE
Does it work with Yii2?

### ISSUE THREAD

**Issue by Torys87** [janisto/yii-ycm#8]
hi,

I use this module in my Yii1 projects and would like to use it in Yii2.
Does this module work with yii2?
Or, if not...

Are you going to integrate it in Yii2 in the future?

**Comment by janisto** [comment]
This is for Yii1 only. When I have the time, I'll do a version for Yii2, too.

**Comment by janisto** [comment]
If you are interested in early development stuff, checkout https://github.com/janisto/yii2-ycm
