### ISSUE TITLE
Disable Create/Update/Delete for specific Model

### ISSUE THREAD

**Issue by marcheluis** [janisto/yii-ycm#9]
I would like to know if there is any way to disable Create/Update/Delete for a certain Model, in my case there is some data i do not want to let the person using the Conten Manager to delete even by accident.

**Comment by janisto** [comment]
You can always exclude that model from ycm.

```
'ycm'=>array(
    'username'=>'xxx',
    'password'=>'xxx',
    'registerModels'=>array(
        'application.models.*',
    ),
    'excludeModels'=>array(
        'User',
    ),
),
```

**Comment by marcheluis** [comment]
Thank you for your response, but i guess i didn't really explain myself well enough. I still want to have the model available for updating, just disable create/delete. I could just make some edit's and hide the buttons using Javascript and/or CSS, but i would like to know if there is a better way.

**Comment by janisto** [comment]
That kind of feature is not currently supported.

**Comment by janisto** [comment]
Hi, could you grab that latest code from master and try this in your models:

```
class Sample extends CActiveRecord
{
    /**
     * Admin variables (ycm module)
     */
    public $adminNames=array('Samples','sample','samples'); // admin interface, singular, plural
    public $downloadExcel=true; // Download Excel
    public $downloadMsCsv=true; // Download MS CSV
    public $downloadCsv=true; // Download CSV
    public $hideCreateAction=true;
    public $hideUpdateAction=true;
    public $hideDeleteAction=true;

    ...
}
```

Let me know what you think about it.

**Comment by marcheluis** [comment]
Thanks a lot, it's exactly what i was looking for.
